# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.quotes_api import QuotesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestQuotesApi(unittest.TestCase):
    """QuotesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.quotes_api.QuotesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_quotes_get_historical_quotes(self):
        """Test case for quotes_get_historical_quotes

        History  # noqa: E501
        """
        pass

    def test_quotes_get_quotes(self):
        """Test case for quotes_get_quotes

        Latest  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
