# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.positions_api import PositionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPositionsApi(unittest.TestCase):
    """PositionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.positions_api.PositionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_positions_get_position(self):
        """Test case for positions_get_position

        Position info  # noqa: E501
        """
        pass

    def test_positions_get_positions(self):
        """Test case for positions_get_positions

        All  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
