# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.performances_api import PerformancesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPerformancesApi(unittest.TestCase):
    """PerformancesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.performances_api.PerformancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_performances_get_performance(self):
        """Test case for performances_get_performance

        Year  # noqa: E501
        """
        pass

    def test_performances_get_performances(self):
        """Test case for performances_get_performances

        All  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
