# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.orders_api import OrdersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.orders_api.OrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_orders_cancel_order(self):
        """Test case for orders_cancel_order

        Cancellation  # noqa: E501
        """
        pass

    def test_orders_get_historical_orders(self):
        """Test case for orders_get_historical_orders

        History  # noqa: E501
        """
        pass

    def test_orders_get_order(self):
        """Test case for orders_get_order

        Order info  # noqa: E501
        """
        pass

    def test_orders_get_orders(self):
        """Test case for orders_get_orders

        Recent  # noqa: E501
        """
        pass

    def test_orders_modify_order(self):
        """Test case for orders_modify_order

        Modification  # noqa: E501
        """
        pass

    def test_orders_preview_modify_order(self):
        """Test case for orders_preview_modify_order

        Validate modification  # noqa: E501
        """
        pass

    def test_orders_preview_order(self):
        """Test case for orders_preview_order

        Validate new  # noqa: E501
        """
        pass

    def test_orders_preview_order_costs(self):
        """Test case for orders_preview_order_costs

        Costs  # noqa: E501
        """
        pass

    def test_orders_register_order(self):
        """Test case for orders_register_order

        New  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
