# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.instruments_response_model import InstrumentsResponseModel  # noqa: E501
from swagger_client.rest import ApiException


class TestInstrumentsResponseModel(unittest.TestCase):
    """InstrumentsResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstrumentsResponseModel(self):
        """Test InstrumentsResponseModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.instruments_response_model.InstrumentsResponseModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
