# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class KidInfoModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'kid_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'kid_id': 'kidId'
    }

    def __init__(self, name=None, kid_id=None, _configuration=None):  # noqa: E501
        """KidInfoModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._kid_id = None
        self.discriminator = None

        self.name = name
        self.kid_id = kid_id

    @property
    def name(self):
        """Gets the name of this KidInfoModel.  # noqa: E501

        Name of the document  # noqa: E501

        :return: The name of this KidInfoModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this KidInfoModel.

        Name of the document  # noqa: E501

        :param name: The name of this KidInfoModel.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def kid_id(self):
        """Gets the kid_id of this KidInfoModel.  # noqa: E501

        Id of the document  # noqa: E501

        :return: The kid_id of this KidInfoModel.  # noqa: E501
        :rtype: str
        """
        return self._kid_id

    @kid_id.setter
    def kid_id(self, kid_id):
        """Sets the kid_id of this KidInfoModel.

        Id of the document  # noqa: E501

        :param kid_id: The kid_id of this KidInfoModel.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and kid_id is None:
            raise ValueError("Invalid value for `kid_id`, must not be `None`")  # noqa: E501

        self._kid_id = kid_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KidInfoModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KidInfoModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KidInfoModel):
            return True

        return self.to_dict() != other.to_dict()
