# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class NewOrderModelOptionLeg(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'side': 'str',
        'instrument_id': 'str'
    }

    attribute_map = {
        'side': 'side',
        'instrument_id': 'instrumentId'
    }

    def __init__(self, side=None, instrument_id=None, _configuration=None):  # noqa: E501
        """NewOrderModelOptionLeg - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._side = None
        self._instrument_id = None
        self.discriminator = None

        self.side = side
        self.instrument_id = instrument_id

    @property
    def side(self):
        """Gets the side of this NewOrderModelOptionLeg.  # noqa: E501

        Buy or sell  # noqa: E501

        :return: The side of this NewOrderModelOptionLeg.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this NewOrderModelOptionLeg.

        Buy or sell  # noqa: E501

        :param side: The side of this NewOrderModelOptionLeg.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and side is None:
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501
        allowed_values = ["buy", "sell"]  # noqa: E501
        if (self._configuration.client_side_validation and
                side not in allowed_values):
            raise ValueError(
                "Invalid value for `side` ({0}), must be one of {1}"  # noqa: E501
                .format(side, allowed_values)
            )

        self._side = side

    @property
    def instrument_id(self):
        """Gets the instrument_id of this NewOrderModelOptionLeg.  # noqa: E501

        Instrument Id  # noqa: E501

        :return: The instrument_id of this NewOrderModelOptionLeg.  # noqa: E501
        :rtype: str
        """
        return self._instrument_id

    @instrument_id.setter
    def instrument_id(self, instrument_id):
        """Sets the instrument_id of this NewOrderModelOptionLeg.

        Instrument Id  # noqa: E501

        :param instrument_id: The instrument_id of this NewOrderModelOptionLeg.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and instrument_id is None:
            raise ValueError("Invalid value for `instrument_id`, must not be `None`")  # noqa: E501

        self._instrument_id = instrument_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NewOrderModelOptionLeg, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewOrderModelOptionLeg):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NewOrderModelOptionLeg):
            return True

        return self.to_dict() != other.to_dict()
