# coding: utf-8

"""
    BinckBank.OpenApi

      BinckBank OpenAPI is an API Platform to access BinckBank's trading services.    Curious? Request your access key after reading the documentation on Github: https://github.com/binckbank-api/client-js#binck-openapi-documentation      # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SessionModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_number': 'str',
        'internal_session_id': 'str'
    }

    attribute_map = {
        'account_number': 'accountNumber',
        'internal_session_id': 'internalSessionId'
    }

    def __init__(self, account_number=None, internal_session_id=None, _configuration=None):  # noqa: E501
        """SessionModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._account_number = None
        self._internal_session_id = None
        self.discriminator = None

        self.account_number = account_number
        self.internal_session_id = internal_session_id

    @property
    def account_number(self):
        """Gets the account_number of this SessionModel.  # noqa: E501

        The number of the account  # noqa: E501

        :return: The account_number of this SessionModel.  # noqa: E501
        :rtype: str
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number):
        """Sets the account_number of this SessionModel.

        The number of the account  # noqa: E501

        :param account_number: The account_number of this SessionModel.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and account_number is None:
            raise ValueError("Invalid value for `account_number`, must not be `None`")  # noqa: E501

        self._account_number = account_number

    @property
    def internal_session_id(self):
        """Gets the internal_session_id of this SessionModel.  # noqa: E501

        The internal session ID  # noqa: E501

        :return: The internal_session_id of this SessionModel.  # noqa: E501
        :rtype: str
        """
        return self._internal_session_id

    @internal_session_id.setter
    def internal_session_id(self, internal_session_id):
        """Sets the internal_session_id of this SessionModel.

        The internal session ID  # noqa: E501

        :param internal_session_id: The internal_session_id of this SessionModel.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and internal_session_id is None:
            raise ValueError("Invalid value for `internal_session_id`, must not be `None`")  # noqa: E501

        self._internal_session_id = internal_session_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SessionModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SessionModel):
            return True

        return self.to_dict() != other.to_dict()
